### ISSUE TITLE
Implement a functionality to create blogs using mongodb 

### ISSUE THREAD

**Issue by Mudassirkhan2** [Bug-Bounty-Brigade/Bug-Bounty-Brigade-backend#1]
Implement a functionality to create blogs using mongodb
https://www.figma.com/file/FbrH4DimveC2uqY74UYn6F/Bug-Bounty-Brigade?type=design&node-id=61-344&mode=design&t=JfhfZFvLJ43LJcda-0

figma file for ui

**Comment by ManasVerma007** [comment]
okay !
